//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterieClasa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaterieClasa()
        {
            this.Absentas = new HashSet<Absenta>();
            this.Notas = new HashSet<Nota>();
        }
    
        public int ID { get; set; }
        public int IDClasa { get; set; }
        public int IDMaterie { get; set; }
        public Nullable<int> OreSaptamanal { get; set; }
        public Nullable<int> IDProfesor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Absenta> Absentas { get; set; }
        public virtual Clasa Clasa { get; set; }
        public virtual Materie Materie { get; set; }
        public virtual Profesor Profesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nota> Notas { get; set; }
    }
}
