//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota
    {
        public int ID { get; set; }
        public int IDElev { get; set; }
        public int IDMaterieClasa { get; set; }
        public Nullable<int> Nota1 { get; set; }
        public System.DateTime DataNota { get; set; }
    
        public virtual Elev Elev { get; set; }
        public virtual MaterieClasa MaterieClasa { get; set; }
    }
}
