//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilizator()
        {
            this.Elevs = new HashSet<Elev>();
            this.Profesors = new HashSet<Profesor>();
            this.UtilizatorAsteptares = new HashSet<UtilizatorAsteptare>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Parola { get; set; }
        public int IDFunctie { get; set; }
        public string Email { get; set; }
        public string Prenume { get; set; }
        public string Nume { get; set; }
        public bool ContActiv { get; set; }
        public Nullable<int> IDElev { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Elev> Elevs { get; set; }
        public virtual Elev Elev { get; set; }
        public virtual Functie Functie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profesor> Profesors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UtilizatorAsteptare> UtilizatorAsteptares { get; set; }
    }
}
